### ISSUE TITLE
Black frame appears to the main ComfyUI interface when the latest ComfyUI-3D-Pack is installed.

### ISSUE THREAD

**Issue by o-l-l-i** [MrForExample/ComfyUI-3D-Pack#343]
I updated yesterday ComfyUI nodes in my local install (Windows) using ComfyUI Manager "Update all" option. 

After the update and restart, everything in the boot-up process went seemingly OK, no crashes or or such. However, I noticed that I had a black extra frame in the view which I did not have earlier. See the screenshot below. There are also a few buttons and UI elements in the bottom-left corner, but the buttons are not functioning.

I didn't have time yesterday to look at this issue, but today I started to check what might be causing it, so I just disabled custom nodes in chunks by moving them out of the folder and reloading, to quickly isolate and see what might cause it. 

So, I managed to isolate this to to ComfyUI-3D-Pack. It might not be necessarily the reason for this, but at least when the latest version is active, this happens. It could be possibly some kind of conflict with the other numerous custom nodes I have installed?
It did not seem to matter either if I had the new menu system enabled by selecting the top menu in settings (Menu/Use new menu and workflow management.)

![20241011_comfy_black_bars2](https://github.com/user-attachments/assets/cc996de8-ce7f-4e29-a34b-08b0dab6453d)

Anyway, if someone knows what might be the cause, that would be appreciated.

**Comment by jakechai** [comment]
check this: https://github.com/MrForExample/ComfyUI-3D-Pack/issues/291#issuecomment-2329839635

**Comment by JasonS09** [comment]
I'm having the same issue after I updated ComfyUI. I have the most recent version of ComfyUI-3D-Pack.

**Comment by MrForExample** [comment]
Hi all, I identified the root cause and now issue is solved, https://github.com/MrForExample/ComfyUI-3D-Pack/pull/325#issuecomment-2420847505

**Comment by jakechai** [comment]
I am afraid it still not working properly for the mesh and 3dgs preview.
![stillnotworking](https://github.com/user-attachments/assets/faa6ab87-5780-4804-b6bf-02398a6051f8)

**Comment by jakechai** [comment]
And even more. The preview nodes went red and the UI stopped refreshing when I returned to the `--front-end-version Comfy-Org/ComfyUI_legacy_frontend@latest` workaround.
![stillnotworking2](https://github.com/user-attachments/assets/86674cbe-ff88-40dc-8475-cd16bfe677e9)

**Comment by jakechai** [comment]
I found that the mesh and 3DGS previews pop up in the menu when first loaded but go back into place after you move your canvas to where the preview nodes exit.
![stillnotworking](https://github.com/user-attachments/assets/faa6ab87-5780-4804-b6bf-02398a6051f8)
![works](https://github.com/user-attachments/assets/609014c8-e0da-4627-9f2f-a5c38339af0b)

**Comment by jakechai** [comment]
When I returned to the `--front-end-version Comfy-Org/ComfyUI_legacy_frontend@latest` workaround, the preview nodes went red and the UI stopped refreshing,  never need it again.
![stillnotworking2](https://github.com/user-attachments/assets/86674cbe-ff88-40dc-8475-cd16bfe677e9)

**Comment by pvp-by** [comment]
The issue is still relevant - 04 dec 2024

**Comment by nonno-cicala** [comment]
I still have this issue with updated ComfyUI ( https://github.com/comfyanonymous/ComfyUI/commit/57f330caf91af37dda67c4202bb27cdebb7161d8 ) and updated ComfyUI-3D-Pack ( a35a737676cf3cbb23360d98032870e242dae199 ).
If I try the `--front-end-version Comfy-Org/ComfyUI_legacy_frontend@latest` the interface is stuck and broken (as showed in https://github.com/MrForExample/ComfyUI-3D-Pack/issues/343#issuecomment-2423478831 )
